version: '3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    image: skhfh/foodgram_backend
    volumes:
      - static:/backend_static
      - media:/media
    env_file: .env
    depends_on:
      - db
  frontend:
    image: skhfh/foodgram_frontend
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static
  nginx:
    image: skhfh/foodgram_nginx
    env_file: .env
    ports:
      - 7000:80
    volumes:
      - static:/staticfiles
      - media:/media
      - ../docs/:/usr/share/nginx/html/api/docs/
